services:
  mariadb:
    image: 'mariadb:latest'
    container_name: 'tune_fun_mariadb'
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_DATABASE: mydatabase
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: myuser
      MARIADB_PASSWORD: secret
    ports:
      - '3305:3306'

  redis:
    image: 'redis:latest'
    container_name: 'tune_fun_redis'
    restart: always
    ports:
      - '6378:6379'

  mongodb:
    image: 'mongo:latest'
    container_name: 'tune_fun_mongodb'
    restart: always
    ports:
      - '27016:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopass
      MONGO_INITDB_DATABASE: mongodatabase