services:
  postgres:
    image: 'postgres:16.2'
    container_name: 'tune_fun_postgres'
    restart: always
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
  redis:
    image: 'redis:7.2.4'
    container_name: 'tune_fun_redis'
    restart: always
    ports:
      - '6378:6379'