services:
  postgres:
    image: 'postgres:latest'
    container_name: 'tune_fun_postgres'
    restart: always
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
  redis:
    image: 'redis:latest'
    container_name: 'tune_fun_redis'
    restart: always
    ports:
      - '6378:6379'

  mongodb:
    image: 'mongo:latest'
    container_name: 'tune_fun_mongodb'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - '27016:27017'
