services:
  mariadb:
    image: 'mariadb:latest'
    restart: always
    environment:
      TZ: Asia/Seoul
      MARIADB_DATABASE: mydatabase
      MARIADB_ROOT_PASSWORD: verysecret
      MARIADB_USER: myuser
      MARIADB_PASSWORD: secret
    ports:
      - '3305:3306'
  redis:
    image: 'redis:latest'
    restart: always
    ports:
      - '6378:6379'
