spring:
  datasource:
    url: jdbc:mariadb://localhost:3305/mydatabase
    username: root
    password: verysecret
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100

  data:
    redis:
      host: localhost
      port: 6378
    mongodb:
      host: localhost
      port: 27016
      database: mydatabase
      username: root
      password: secret
      authentication-database: admin

  thymeleaf:
    enabled: false

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail-username}
    password: ${gmail-password}
    properties:
      mail:
        debug: true
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  config:
    import: optional:aws-secretsmanager:tunefun_dev_secrets
  cloud:
    aws:
      secretsmanager:
        region: ap-northeast-2

jwt:
  accessTokenValidity: 3d
  refreshTokenValidity: 30d
  secret: x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkX

otp:
  validity: 3m

fcm:
  sdk-file: tunefun-firebase-adminsdk.json
  project-id: tunefun-9186f

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/com.tune_fun-open-api-3.0.1.json