spring:
  docker:
    compose:
      enabled: false
  datasource:
    # 인프라 구축 필요
    url: jdbc-secretsmanager:mariadb://~~~~~~~~~~~~
    username: tunefun_staging_rds_secret
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMariaDBDriver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100

  data:
    # 인프라 구축 필요
    redis:
      host: ${redis-host}
      port: ${redis-port}
    mongodb:
      host: ${mongodb-host}
      port: ${mongodb-port}
      database: ${mongodb-databasse}
      username: ${mongodb-username}
      password: ${mongodb-password}

  thymeleaf:
    enabled: false

  flyway:
    enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  config:
    import: optional:aws-secretsmanager:tunefun_staging_secrets
  cloud:
    aws:
      secretsmanager:
        region: ap-northeast-2

jwt:
  accessTokenValidity: 3m
  refreshTokenValidity: 30d
  secret: ${jwt-secret}

fcm:
  sdk-file: tunefun-firebase-adminsdk.json
  project-id: tunefun-9186f

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/com.tune_fun-open-api-3.0.1.json
    path: /swagger
