spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 17700
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 1000
  thymeleaf:
    enabled: false
  flyway:
    enabled: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: 127.0.0.1
    username: habin
    password: qpalzm0915()
    properties:
      mail:
        debug: true
        smtp:
          timeout: 5000
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
      transport:
        protocol: smtp
      default-encoding: UTF-8
    protocol: smtp
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: aaaa
            client-secret: bbbb
            redirect-uri: "cccclogin/oauth2/code/google"
            scope:
              - profile
              - email
          apple:
            client-name: Apple
            client-id: aaaa
            client-secret: bbbb
            redirect-uri: "cccc/login/oauth2/code/apple"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - name
              - email
          instagram:
            client-name: Instagram
            provider: instagram
            client-id: aaaa
            client-secret: bbbb
            redirect-uri: "cccc/login/oauth2/code/instagram"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - user_profile
              - user_media
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize?scope=name%20email&response_mode=form_post
            token-uri: https://appleid.apple.com/auth/token
          instagram:
            authorization-uri: https://api.instagram.com/oauth/authorize
            token-uri: https://api.instagram.com/oauth/access_token

fcm:
  sdk-file: tunefun-firebase-adminsdk.json
  project-id: tunefun-9186f

jwt:
  accessTokenValidity: 3m
  refreshTokenValidity: 30d
  secret: x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkX

event:
  sqs:
    test:
      queue-name: test
      message-group-id: test

otp:
  validity: 3m
