spring:
  docker:
    compose:
      enabled: false
  datasource:
    # 인프라 구축 필요
    url:
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 100

  data:
    # 인프라 구축 필요
    redis:
      host:
      port:
    mongodb:
      host:
      port:
      database:
      username:
      password:


  thymeleaf:
    enabled: false

jwt:
  accessTokenValidity: 3m
  refreshTokenValidity: 30d
  secret: x/A?D(G+KbPeShVmYq3t6v9y$B&E)H@McQfTjWnZr4u7x!z%C*F-JaNdRgUkXp2s5v8y/B?D(G+KbPeShVmYq3t6w9z$C&F)H@McQfTjWnZr4u7x!A%D*G-KaNdRgUkX

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /docs/com.tune_fun-open-api-3.0.1.json


aws:
  # 인프라 구축 필요
  access-key-id:
  secret-access-key:
  default-region:
  s3-bucket-name: